### ISSUE TITLE
Doesn't work since yesterday

### ISSUE THREAD

**Issue by mhanu** [andrew0/SiriusXM#11]
Since yesterday I only get an exception when I tried to stream a channel.

28.Nov 2018 13:13:57 <SiriusXM>: Received error 100 Successful
----------------------------------------

Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 313, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 341, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "sxm.py", line 318, in do_GET
    data = self.sxm.get_playlist(self.path.rsplit('/', 1)[1][:-5])
  File "sxm.py", line 233, in get_playlist
    res = self.session.get(url, params=params)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 492, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 466, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 400, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python3/dist-packages/requests/models.py", line 293, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 353, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?

**Comment by djkraven** [comment]
I am getting the same errors using Python 3.6.7

**Comment by alexj212** [comment]
I had the same issue, I tracked it down to line 188, change the status check from 
elif status == 0:
to 
elif message_code != 100

Then you should be good to go, I will create a PR when I get home

**Comment by djkraven** [comment]
Made the change and confirm it is working for me too. Thank you. Now find the ID for Rockin XMAS :-)
