### ISSUE TITLE
Error when trying to stream on Onkyo receiver

### ISSUE THREAD

**Issue by djkraven** [andrew0/SiriusXM#12]
The Onkyo TX-NR709 has a favorite option they can custom stream links added to. I put the link http://192.168.1.200:8888/9486.m3u8 that works using VLC in the Onkyo and it generates the error information below. I don't have details on what the Onkyo supports but it will play acc streams. This is one that works http://wfuv-onair.streamguys.org:80/onair-aacplus. I realize sxm.py is different than the wfuv one and it may not be possible. Any thoughts or suggestions?

Onkyo:
Connection Error.
The server connection could not be established or was terminated early. Please try again later.

sxm.py:
Exception happened during processing of request from ('192.168.1.50', 47958)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 348, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 721, in __init__
    self.handle()
  File "/usr/lib/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
  File "/usr/lib/python3.6/http/server.py", line 406, in handle_one_request
    method()
  File "./sxm.py", line 324, in do_GET
    self.wfile.write(bytes(data, 'utf-8'))
  File "/usr/lib/python3.6/socketserver.py", line 800, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by andrew0** [comment]
That error means that the socket was closed while it was transmitting data, and it shouldn't cause a crash I don't think. Are you sure that your receiver supports HLS (m3u) streams with AES-128 encryption? It's possible that the receiver is reading until it sees that the stream requires AES-128 decryption and exits because it's unsupported.

**Comment by djkraven** [comment]
I am not finding a lot of details on the specification and what is supported. You are probably right that it does not support encryption. Is there an option or way to add an option to not use encryption?
