### ISSUE TITLE
Authentication Failure Suddenly

### ISSUE THREAD

**Issue by LongJohnTX** [andrew0/SiriusXM#18]
First of all, thanks for such a great project.  It worked great for me for months, but just today (9/18/19), I was no longer able to stream due to an authentication failure:

WARNING:/usr/local/lib/python3.7/dist-packages/sxm/client.py:Received status code 403 for path 'modify/authentication'
ERROR:/usr/local/lib/python3.7/dist-packages/sxm/client.py:Unable to authenticate because login failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tenacity/__init__.py", line 361, in call
    result = fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/sxm/client.py", line 233, in authenticate
    raise AuthenticationError("Reset session")
sxm.client.AuthenticationError: Reset session

I found that by changing the FakeUserAgent signature from "chrome" to "firefox" in client.py, I was able to get it going again.  I don't know if they had put a trap in the handling on their end to fix something that was broken in the Chrome browser, or if they are trying to pick off rogue clients by their User-agent signature.

With your knowledge of the handshaking, you may be able to diagnose this more deeply than I am currently able to.

**Comment by simondsmason** [comment]
Hi, I just started playing around with this and got the unable to authenticate:

ERROR:C:\Users\simon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\sxm\client.py:Unable to authenticate because login failed

I tried the fix above - replacing chrome with firefox in client.py but this didn't make any difference.

Any ideas?  Thanks.

**Comment by aherna04** [comment]
Here's the fix: 
https://github.com/toioiz/sxm-client/commit/bd80d978896016c42c8d29108d57ae03021a191d

**Comment by jusplainmike** [comment]
> Here's the fix:
> [toioiz@bd80d97](https://github.com/toioiz/sxm-client/commit/bd80d978896016c42c8d29108d57ae03021a191d)

Are you sure this is a fix? I changed it and it still gives me auth failure.
