### ISSUE TITLE
Authentication Failure

### ISSUE THREAD

**Issue by afreeman28** [andrew0/SiriusXM#24]
Unable to authenticate with script. Receive the following: 

` <SiriusXM>: Unable to authenticate because login failed
 <SiriusXM>: Unable to authenticate
<SiriusXM>: Unable to get channel list
Traceback (most recent call last):
raceback (most recent call last):
  File "sxm.py", line 362, in <module>
    channels = list(sorted(sxm.get_channels(), key=lambda x: (not x.get('isFavorite', False), int(x.get('siriusChannelNumber', 9999)))))
  File "sxm.py", line 362, in <lambda>
    channels = list(sorted(sxm.get_channels(), key=lambda x: (not x.get('isFavorite', False), int(x.get('siriusChannelNumber', 9999)))))
AttributeError: 'NoneType' object has no attribute 'get'
`

I am using trying to run the scrip via `sudo python3 sxm.py username password -p 8888`

What am I missing? is this script still working ?

**Comment by afreeman28** [comment]
found resolutions in #20
