### ISSUE TITLE
Unable to authenticate, unable to get channel list

### ISSUE THREAD

**Issue by hubbardre** [andrew0/SiriusXM#34]
Did this stop working for anyone else recently? I now get this error. I have already updated SXMAUTH to SXMAUTHNEW and its been working for me for months. 

13.Jun 2021 19:41:08 <SiriusXM>: Unable to authenticate
13.Jun 2021 19:41:08 <SiriusXM>: Unable to get channel list
----------------------------------------
Exception happened during processing of request from ('192.168.0.120', 59983)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "sxm.py", line 323, in do_GET
    data = sxm.get_playlist(self.path.rsplit('/', 1)[1][:-5])
  File "sxm.py", line 227, in get_playlist
    guid, channel_id = self.get_channel(name)
  File "sxm.py", line 313, in get_channel
    if x.get('name', '').lower() == name or x.get('channelId', '').lower() == name or x.get('siriusChannelNumber') == name:
AttributeError: 'NoneType' object has no attribute 'get'
----------------------------------------
13.Jun 2021 19:41:08 <SiriusXM>: Unable to authenticate
13.Jun 2021 19:41:08 <SiriusXM>: Unable to get channel list
----------------------------------------
Exception happened during processing of request from ('192.168.0.120', 59984)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "sxm.py", line 323, in do_GET
    data = sxm.get_playlist(self.path.rsplit('/', 1)[1][:-5])
  File "sxm.py", line 227, in get_playlist
    guid, channel_id = self.get_channel(name)
  File "sxm.py", line 313, in get_channel
    if x.get('name', '').lower() == name or x.get('channelId', '').lower() == name or x.get('siriusChannelNumber') == name:
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by hubbardre** [comment]
Figured it out for anyone else that wants this fixed. Looks like they updated their cookies again. Need to update AWSELB to AWSALB.

**Comment by rustic** [comment]
> Figured it out for anyone else that wants this fixed. Looks like they updated their cookies again. Need to update AWSELB to AWSALB.

Thanks @hubbardre . This edit worked for me too. You saved me a lot of frustration!
